In [1]:
import pandas as pd
import json

In [2]:
with open("batting-2024.json","r") as file:
    batting_data = json.load(file)

with open("bowling-2024.json","r") as file:
    bowling_data = json.load(file)

batting_df = pd.DataFrame(batting_data)
bowling_df = pd.DataFrame(bowling_data)

In [3]:
batting_df.head()

,StrikerName,PlayerId,Matches,PlayerDOB,RightHandedBat,Nationality,TCompetitionID,TStrikerID,TTeamID,TeamCode,...,NotOuts,BattingAveragesss,FiftyPlusRuns,Centuries,DoubleCenturies,HighestScore,BattingAverage,Catches,Stumpings,ClientPlayerID
0,Virat Kohli,2,5,0000-00-00,true,Indian,148,2018-wicb00000000002-47ea5a6ae99a11,19,RCB,...,2,158.00,2,1,0,113*,105.33,4,0,164
1,Riyan Parag,189,4,0000-00-00,true,Indian,148,2019-100mb00000000189-ac8c327a44b711,18,RR,...,2,92.50,2,0,0,84*,92.50,0,0,4445
2,Sanju Samson,190,4,0000-00-00,true,Indian,148,2019-100mb00000000190-c62cbae544b711,18,RR,...,1,178.00,2,0,0,82*,59.33,4,0,258
3,Heinrich Klaasen,202,4,0000-00-00,true,Overseas,148,2019-100mb00000000202-438eed6944ba11,20,SRH,...,2,88.50,2,0,0,80*,88.50,1,0,3869
4,Shubman Gill,62,4,0000-00-00,true,Indian,148,2019-100mb00000000062-8fa4884a17f311,35,GT,...,1,164.00,1,0,0,89*,54.67,1,0,3761

In [4]:
print(len(batting_df),len(bowling_df))

105 69

In [5]:
bowling_df.head()

,BowlerName,RightHandedBat,Nationality,TeamCode,TeamName,Matches,CompetitionID,Innings,TeamID,BowlerID,...,MatchRuns,MatchWickets,BBIW,BBMW,Maidens,MaidenWickets,FourWickets,FiveWickets,TenWickets,ClientPlayerID
0,Yuzvendra Chahal,true,Indian,RR,Rajasthan Royals,4,148,4,18,2018-100mb00000000010-b76159ade99b11,...,11,3,11/3,11/3,0,0,0,0,0,111
1,Mohit Sharma,true,Indian,GT,Gujarat Titans,4,148,4,35,2019-100mb00000000100-f196053e43f611,...,25,3,25/3,25/3,0,0,0,0,0,1107
2,Mustafizur Rahman,false,Overseas,CSK,Chennai Super Kings,3,148,3,13,2019-100mb00000000258-e46e7f697acb11,...,29,4,29/4,29/4,0,0,1,0,0,1594
3,Mayank Yadav,true,Indian,LSG,Lucknow Super Giants,2,148,2,77,2022-100mb00000000987-e0fbfce6a44911,...,14,3,14/3,14/3,0,0,0,0,0,20585
4,Khaleel Ahmed,true,Indian,DC,Delhi Capitals,4,148,4,14,2018-100mb00000000008-787fc4ece99b11,...,21,2,21/2,21/2,1,1,0,0,0,2964

In [6]:
combined_df = batting_df.merge(bowling_df, on=["ClientPlayerID"], suffixes=('_batting', '_bowling'), how="outer")
combined_df.head()

,StrikerName,PlayerId,Matches_batting,PlayerDOB,RightHandedBat_batting,Nationality_batting,TCompetitionID,TStrikerID,TTeamID,TeamCode_batting,...,InningsWickets,MatchRuns,MatchWickets,BBIW,BBMW,Maidens,MaidenWickets,FourWickets,FiveWickets,TenWickets
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,23,1,23/1,23/1,0,0,0,0,0
1,MS Dhoni,57,4,0000-00-00,true,Indian,148,2019-100mb00000000057-57100cf415ba11,13,CSK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Dinesh Karthik,13,5,0000-00-00,true,Indian,148,2018-100mb00000000013-1031ba8ae99c11,19,RCB,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Travis Head,37,3,0000-00-00,false,Overseas,148,2018-100mb00000000037-4e250de6f88a11,20,SRH,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Rohit Sharma,6,3,0000-00-00,true,Indian,148,2018-100mb00000000006-2cf4bba8e99b11,17,MI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
combined_df.columns

Index(['StrikerName', 'PlayerId', 'Matches_batting', 'PlayerDOB',
       'RightHandedBat_batting', 'Nationality_batting', 'TCompetitionID',
       'TStrikerID', 'TTeamID', 'TeamCode_batting', 'TeamName_batting',
       'CompetitionID_batting', 'TeamID_batting', 'StrikerID',
       'Innings_batting', 'Extras', 'TotalRuns', 'Balls', 'Dotballs',
       'StrikeRate_batting', 'DBPercent', 'DBFreq', 'BdryFreq', 'BdryPercent',
       'RPSS', 'ScoringBalls', 'Ones_batting', 'Twos_batting',
       'Threes_batting', 'Fours_batting', 'Sixes_batting', 'Outs', 'NotOuts',
       'BattingAveragesss', 'FiftyPlusRuns', 'Centuries', 'DoubleCenturies',
       'HighestScore', 'BattingAverage', 'Catches', 'Stumpings',
       'ClientPlayerID', 'BowlerName', 'RightHandedBat_bowling',
       'Nationality_bowling', 'TeamCode_bowling', 'TeamName_bowling',
       'Matches_bowling', 'CompetitionID_bowling', 'Innings_bowling',
       'TeamID_bowling', 'BowlerID', 'LegalBallsBowled', 'TotalRunsConceded',
       'DotBallsBowled', 'DotBallPercent', 'ScoringBallsBowled',
       'BowlingAverage', 'StrikeRate_bowling', 'BowlingSR',
       'BoundaryPercentage', 'BoundaryFrequency', 'EconomyRate', 'OversBowled',
       'Ones_bowling', 'Twos_bowling', 'Threes_bowling', 'Fours_bowling',
       'Sixes_bowling', 'Wides', 'NoBalls', 'Byes', 'LegBye', 'Wickets',
       'InningsRuns', 'InningsWickets', 'MatchRuns', 'MatchWickets', 'BBIW',
       'BBMW', 'Maidens', 'MaidenWickets', 'FourWickets', 'FiveWickets',
       'TenWickets'],
      dtype='object')

In [9]:
combined_df.to_json(path_or_buf="combined-2024.json", orient="records")

In [32]:
len(combined_df)

198